../ulc ./woSt_2.1.1_invalid.ul
../ulc ./woSt_2.1.2a_invalid.ul
../ulc ./woSt_2.1.2b_invalid.ul
../ulc ./woSt_2.1.3_invalid.ul
../ulc ./woSt_2.1_valid.ul
../ulc ./woSt_2.2.1_invalid.ul
../ulc ./woSt_2.2.2_invalid.ul
../ulc ./woSt_2.2.3_invalid.ul
../ulc ./woSt_2.2.4_invalid.ul
../ulc ./woSt_2.2.5_valid.ul
../ulc ./woSt_2.2.6_invalid.ul
../ulc ./woSt_2.2.7_invalid.ul
../ulc ./woSt_2.2_valid.ul
../ulc ./woSt_3.1.1_invalid.ul
../ulc ./woSt_3.1.2_invalid.ul
../ulc ./woSt_3.1.3_invalid.ul
../ulc ./woSt_3.1.4_invalid.ul
../ulc ./woSt_3.1.5_invalid.ul
../ulc ./woSt_3.1.6_invalid.ul
../ulc ./woSt_3.1_valid.ul
../ulc ./woSt_3.2.1_invalid.ul
../ulc ./woSt_3.2.2.a_invalid.ul
../ulc ./woSt_3.2.2.b_invalid.ul
../ulc ./woSt_3.2.2.c_invalid.ul
../ulc ./woSt_3.2.2.d_invalid.ul
../ulc ./woSt_3.2.2.e_invalid.ul
../ulc ./woSt_3.2_valid.ul
../ulc ./woSt_3.3.a_invalid.ul
../ulc ./woSt_3.3.b_invalid.ul
../ulc ./woSt_3.3_valid.ul
